version: "3.8"
services:
  php:
    container_name: php
    build: './docker/php/'
    networks:
      - php-sandbox-network
    volumes:
      - ./php_sandbox/:/var/www/project/
  apache:
    container_name: web
    build: './docker/apache/'
    depends_on:
      - php
      #- mysql
    networks:       
      #- frontend
      - php-sandbox-network
    ports:
      - "8080:80"
    volumes:
      - ./php_sandbox/:/var/www/project/
  redis:
    container_name: redis
    build: './docker/redis/'
    networks: 
      - php-sandbox-network
    ports: 
      - "6379:6379"
#  mysql:
#    image: mysql:5.6.40
#    networks:
#      - backend
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
#  frontend:
  php-sandbox-network: